---
- name: Automatisation des installations
  hosts: VM_DEB12_ADRIEN
  become: true
  vars:
    user_home: "/home/{{ ansible_user }}"
    oh_my_zsh_dir: "{{ user_home }}/.oh-my-zsh"

  tasks:
    - name: Mise à jour des paquets
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600

    - name: Installation des paquets de base
      ansible.builtin.apt:
        pkg:
          - curl
          - wget
          - git
          - unzip
          - hstr
          - exa
          - bat
          - tree
          - btop
          - neofetch
          - ranger
          - pandoc
          - lynx


    - name: Installation de zsh
      ansible.builtin.package:
        name: zsh
        state: present

    - name: Installation de fzf (command-line fuzzy finder)
      ansible.builtin.package:
        name: fzf
        state: present

    - name: Installation de Oh My Zsh
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "{{ oh_my_zsh_dir }}"
        depth: 1
      become: false
      become_user: "{{ ansible_user }}"

    - name: Installation du plugin zsh-autosuggestions
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: "{{ oh_my_zsh_dir }}/custom/plugins/zsh-autosuggestions"
        depth: 1
      become: false
      become_user: "{{ ansible_user }}"
    
    - name: Installation du plugin zsh-completions
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-completions
        dest: "{{ oh_my_zsh_dir }}/custom/plugins/zsh-completions"
        depth: 1
      become: false
      become_user: "{{ ansible_user }}"
    
    - name: Installation du plugin zsh-syntax-highlighting
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "{{ oh_my_zsh_dir }}/custom/plugins/zsh-syntax-highlighting"
        depth: 1
      become: false
      become_user: "{{ ansible_user }}"
    
    - name: Changement du shell par défaut pour zsh
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: /bin/zsh

    - name: Copie du fichier de configuration .zshrc
      ansible.builtin.copy:
        src: ../../config-files/.zshrc
        dest: "{{ user_home }}/.zshrc"
        mode: 0644
      become: false
      become_user: "{{ ansible_user }}"

    - name: Créer un script de récapitulatif des configurations
      ansible.builtin.copy:
        dest: /usr/local/bin/setup-tools_summary.sh
        content: |
          #!/bin/sh
          echo "======================================"
          echo "         Récapitulatif de Setup        "
          echo "======================================"
          echo ""
          
          PACKAGES="curl|wget|git|unzip|hstr|exa|bat|tree|btop|neofetch|ranger|pandoc|lynx"

          echo "1. Packages Installés:"
          dpkg -l | grep -E "$PACKAGES"
          echo ""

          IFS='|' read -r -a PACKAGES_ARRAY <<< "$PACKAGES"
          for package in "${PACKAGES_ARRAY[@]}"; do
            echo "$package:"
            sudo apt show "$package" 2> /dev/null | grep -E 'Package|Version'
            echo ""
          done
          

          echo "======================================"
          echo "     Fin du Récapitulatif Setup        "
          echo "======================================"
        mode: '0755'
      notify:
        - Informer l'utilisateur de la création du script

  handlers:
    - name: Informer l'utilisateur de la création du script
      debug:
        msg: "Le script de récapitulatif a été créé à /usr/local/bin/setup-tools_summary.sh. Vous pouvez l'exécuter avec sudo /usr/local/bin/setup-tools_summary.sh"

  post_tasks:
    - name: Messgae de fin d'installation
      ansible.builtin.debug:
        msg: "Installation compléte."

