# File: playbook-hidora.yml
---
- name: Install c++ development environment
  hosts: hidora_vm
  become: true
  vars:
    docker_arch: amd64

  tasks:
    - name: Fail if not an x86_64 architecture
      ansible.builtin.fail:
        msg: "This playbook is intended only for x86_64 (amd64) architectures."
      when: ansible_architecture != "x86_64"

    - name: Update and upgrade all packages to the latest version
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600
        
    - name: Install required packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
          - build-essential
          - zip


    - name: Add non-privileged user
      ansible.builtin.user:
        name: dev
        state: present
        shell: /bin/bash
        create_home: yes
  
    - name: Add user to sudoers
      ansible.builtin.copy:
        content: "dev ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/dev
        mode: '0440'
   
    - name: Create SSH directory
      ansible.builtin.file:
        path: /home/dev/.ssh
        state: directory
        owner: dev
        group: dev
        mode: '0700'

    - name: Copy SSH public key to non-privileged user
      ansible.builtin.copy:
        src: ~/.ssh/id_rsa.pub
        dest: /home/dev/.ssh/authorized_keys
        owner: dev
        group: dev
        mode: '0600'

